#include<bits/stdc++.h>
#include<gmp.h>
using namespace std;

int main() {
	mpz_t P, G, a, b, x, y, Ka, Kb;
	mpz_inits(P, G, a, b, x, y, Ka, Kb, NULL);
	cout<<"Enter the two publicly known numbers P and G(primitive root of P): ";
	cin>>P>>G;
	gmp_randstate_t randstate;
	gmp_randinit_mt(randstate);
	mpz_urandomm(a, randstate, P);
    gmp_randseed_ui(randstate, time(NULL));
	mpz_urandomm(b, randstate, P);

	gmp_printf("\nPrivate key selected by Alice: %Zd\nPrivate key selected by Bob: %Zd\n", a, b);

	mpz_powm(x, G, a, P);
	mpz_powm(y, G, b, P);

	gmp_printf("\nPublic value for Alice, x = %Zd\nPublic value for Bob, y = %Zd\n", x, y);

	gmp_printf("\nAlice and Bob exchange keys\n");

	gmp_printf("\nAlice recieves: %Zd and Bob recieves: %Zd\n", y, x);

	mpz_powm(Ka, y, a, P);
	mpz_powm(Kb, x, b, P);

	gmp_printf("\nShared secret key generated by Alice: %Zd\nShared secret key generated by Bob: %Zd\n", Ka, Kb);
}
